data:
  raw_path: data/Telco-Customer-Churn.csv
  processed_path: data/clean_data.csv

preprocessing:
  target_column: Churn


model:
  baseline_path: models/baseline_model.pkl
  xgb_path: models/xgb_model.pkl
  scaler_path: models/scaler.pkl
  label_encoders_path: models/label_encoders.pkl


train:
  mode: debug            # valeurs possibles : "debug" ou "production"
  test_size: 0.2
  random_state: 42

baseline_model:
  type: logistic_regression
  C: 1.0
  max_iter: 2000

xgb_model:
  type: xgboost
  max_depth: 15
  learning_rate: 0.5
  n_estimators: 200
  scale_pos_weight: 2.5  # Ratio classe minoritaire / majoritaire
  reg_lambda: 2.0
  reg_alpha: 1.0
  gamma: 0.2
  subsample: 0.5
  colsample_bytree: 0.5

logging:
  log_file_preprocessing: logs/preprocessing.log
  log_file_training: logs/training.log
  log_file_evaluation: logs/evaluation.log
  log_file_predict: logs/predict.log

predict:
  input_path: data/raw_data_churn_test.csv
  output_path: outputs/predictions.csv
  model_to_use: xgb  # ou "baseline"
  model_registry_name: customerChurnModelXgboost
  version_to_use: 4  # version_to_use: "latest"  # ou "latest"


artifacts:
  path: outputs/

mlflow:
  experiment_name: "telco_churn_experiment"
  tracking_uri: "http://localhost:5000"
  tags:
    project: "telco_churn"
    owner: "thierrydev19"
    phase: "full-tracking"
